# Generated by Django 5.0.1 on 2024-05-01 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='patientinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=30)),
                ('pgname', models.CharField(max_length=30)),
                ('pphone', models.IntegerField()),
                ('pemail', models.CharField(max_length=30)),
                ('pdate', models.DateTimeField()),
                ('pdoctor', models.CharField(max_length=30)),
            ],
        ),
    ]
