# Generated by Django 5.0.1 on 2024-05-01 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigin', '0002_patientinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientinfo',
            name='pphone',
            field=models.CharField(max_length=15),
        ),
    ]
