# Generated by Django 5.0.1 on 2024-05-08 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigin', '0004_alter_patientinfo_pdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientinfo',
            name='pemail',
            field=models.CharField(max_length=50),
        ),
    ]
