# Generated by Django 5.0.1 on 2024-05-01 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appno', models.IntegerField(primary_key=True, serialize=False)),
                ('patientname', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('doctorname', models.CharField(max_length=20)),
            ],
        ),
    ]
